### ISSUE TITLE
cant seem to start

### ISSUE THREAD

**Issue by joshfryart** [lightaime/camel#91]
```
(camel) C:\Users\joshu\Documents\_aipython\_useful\CAMEL agnet\camel\camel\agents>python role_playing.py
Traceback (most recent call last):
  File "C:\Users\joshu\Documents\_aipython\_useful\CAMEL agnet\camel\camel\agents\role_playing.py", line 8, in <module>
    from .chat_agent import ChatAgent
ImportError: attempted relative import with no known parent package
```

any help would be good.

**Comment by Obs01ete** [comment]
Hi @joshfryart ! Please install the package with `pip install -e .`. It is not supposed to be used from within the repository.

**Comment by Obs01ete** [comment]
Also @joshfryart thank you for putting our project into the forlder "_useful". We appreciate it!

**Comment by joshfryart** [comment]
I did run pip install -e . and it still has the same issue :/ hmmmmm

**Comment by lightaime** [comment]
Not sure if this is a path problem in Windows. We will look into it. Thanks for reporting it @joshfryart

**Comment by 7Moses** [comment]
Similar here (Mac), 

Successfully built camel

Successfully installed camel-0.0.1

(camel) moses@MosesMoses ~/imaginativereasoning/camel/camel/agents (drafting)$ python role_playing.py                                   
Traceback (most recent call last):
  File "/Users/moses/imaginativereasoning/camel/camel/agents/role_playing.py", line 7, in <module>
    from .chat_agent import ChatAgent
ImportError: attempted relative import with no known parent package

I went for https://iq-inc.com/importerror-attempted-relative-import/ but it did not work out,

**Comment by lightaime** [comment]
@joshfryart @7Moses let me if it works by run the script example/ai_society/role_playing.py. Thanks again for reporting this.

**Comment by joshfryart** [comment]
`Traceback (most recent call last):
  File "C:\Users\joshu\Documents\_aipython\_useful\camel\examples\ai_society\role_playing.py", line 3, in <module>
    from .camel.agents import RolePlaying
ImportError: attempted relative import with no known parent package`

**Comment by Obs01ete** [comment]
@joshfryart please try:
1. pip install -e .
2. run the script examples/ai_society/role_playing.py

**Comment by 7Moses** [comment]
Thank you for getting back to me, appreciated 

(Just in case: I did not use conda, see below for my .pyenv set up, ) 

I ran $ python /examples/ai_society/role_playing.py like this 

(camel) moses@MosesMoses ~/imaginativereasoning/camel/examples/ai_society (drafting)$ python /examples/ai_society/role_playing.py  

Nope, No such file, 

(camel) moses@MosesMoses ~/imaginativereasoning/camel/examples/ai_society (drafting)$ python /Users/moses/imaginativereasoning/camel/examples/ai_society/role_playing.py  

Traceback (most recent call last):

  File "/Users/moses/imaginativereasoning/camel/examples/ai_society/role_playing.py", line 49, in <module>
    main()
  File "/Users/moses/imaginativereasoning/camel/examples/ai_society/role_playing.py", line 16, in main
    role_play_session = RolePlaying("Python Programmer", "Stock Trader",
  File "/Users/moses/imaginativereasoning/camel/camel/agents/role_playing.py", line 39, in __init__
    self.specified_task_prompt = task_specify_agent.specify_task(
  File "/Users/moses/imaginativereasoning/camel/camel/agents/task_agent.py", line 56, in specify_task
    specified_task_msgs, terminated, _ = self.step(task_msg)
  File "/Users/moses/.pyenv/versions/camel/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/moses/.pyenv/versions/camel/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/moses/.pyenv/versions/camel/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1178f3b50 state=finished raised AuthenticationError>]

(camel) moses@MosesMoses ~/imaginativereasoning/camel/examples/ai_society (drafting)$ 

Best to you,

**Comment by joshfryart** [comment]
> @joshfryart please try:
> 
>     1. pip install -e .
> 
>     2. run the script examples/ai_society/role_playing.py

this worked. Thanks for missing my oversight. Having fun now 👯

**Comment by Obs01ete** [comment]
@joshfryart enjoy!

**Comment by luqiang21** [comment]
I am curious why it doesn't work when I followed `Install CAMEL from source with poetry (Recommended):`? I can see `camel` exist in python3 console, but not able to run `python3 examples/ai_society/role_playing.py` which gave me no module named `camel`
